version: "3"

services:
  api:
    build: .
    image: dsolab/passets-api:1.0.0
    container_name: passets-api
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=<elasticsearch-host>:9200
      - ELASTICSEARCH_INDEX=logstash-passets
      - SECRET=<dsolab-passets-api-secret>
    ports:
      - "8081:8080"