server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: passets-api
  http:
    converters:
      preferred-json-mapper: gson
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.defvul: ${LOG_LEVEL:info}
elasticsearch:
  url: ${ELASTICSEARCH_URL:http://passets-elasticsearch:9200}
  index: ${ELASTICSEARCH_INDEX:logstash-passets}
secret: ${SECRET:dsolabpassetsapisecret}
data-save-date: ${DATA_SAVE_DAY:30}